### ISSUE TITLE
saved paths in obj.dirs is os incompatible

### ISSUE THREAD

**Issue by kianwei96** [grero/DataProcessingTools#63]
for objects generated on aws/linux, the obj.dirs list contains paths in this format:
'picasso/20181105/session01/array01/channel002/cell01'
whereas objects generated on windows store paths in this format:
'Documents\\20181105\\session01\\array01\\channel002\\cell01'

The DPT.levels.get_level_name and other library methods use python os library to parse the path strings. Calling DPT.levels on AWS created objects in Windows will produce an error, and vice-versa, as the python os library behaves differently depending on the home OS.

**Comment by grero** [comment]
That's a really good point. I think we have to decided on a canonical format to save things in, and then convert to the that reads the object. This is similar to how e.g. git does it with line endings. The standard practice is to record unix style line endings internally, and then covert to e.g. Windows line endings when checking things out. So, we could modified the paths to reflect the current OS when loading the objects.

**Comment by kianwei96** [comment]
I think this library (pathlib) might be useful!

https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f

**Comment by grero** [comment]
That looks promising, thanks!

**Comment by grero** [comment]
Should we then use pathlib.Path on each directory in obj.dirs when we load it? That should take care of converting between windows and unix/mac style paths automatically. It means, though, that the contents of obj.dirs is no longer just strings, but that is probably OK.

**Comment by kianwei96** [comment]
we can still save the obj.dirs as an array of strings right? then just call pathlib.Path() in DPT to do the conversion before using the os library to split it (like we're doing now).

filename = Path("abc\\def\\ghi")
Out[39]: WindowsPath('abc/def/ghi')
filename = Path("abc/def/ghi")
Out[41]: WindowsPath('abc/def/ghi')

**Comment by grero** [comment]
Yes, that's what I had in mind. Ideally, though, we shouldn't require the user to call Path on anything, though, so I'm thinking in the DPObject.load method, we'll call Path on each saved directory, so that the user can use them directly, as we are currently doing.

**Comment by grero** [comment]
See #64 for my suggestion on how to solve this.

**Comment by grero** [comment]
I think we can close this after having merged #66
